import esbuild from "esbuild";
import process from "process";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const pkg = require("./package.json");
const manifest = require("./manifest.json");
const fs = require("fs");

const production = process.argv[2] === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = production;
const outDir = ".";
const outFile = "main.js";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: ["obsidian"],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${outDir}/${outFile}`,
	loader: { ".md": "text", ".png": "dataurl" },
	// The version stamped on files the plugin writes (src/compat.ts). Taken from
	// manifest.json at build time: Obsidian keeps the manifest it read at startup,
	// so plugin.manifest.version can be stale after an update without a restart.
	define: { __HEXMAKER_VERSION__: JSON.stringify(manifest.version) },
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
