// Generated by dev/build-space-icons.mjs — space icon pack (see icons/CREDITS.md).
import spaceAnomaly from "../icons/space-anomaly.svg";
import spaceAsteroid from "../icons/space-asteroid.png";
import spaceAtomOutline from "../icons/space-atom-outline.svg";
import spaceBeaconOutline from "../icons/space-beacon-outline.svg";
import spaceBlackHole from "../icons/space-black-hole.svg";
import spaceComet from "../icons/space-comet.svg";
import spaceDebris from "../icons/space-debris.svg";
import spaceDefenseSatellite from "../icons/space-defense-satellite.svg";
import spaceDotsHex from "../icons/space-dots-hex.svg";
import spaceDoubleRing from "../icons/space-double-ring.svg";
import spaceDustCloud from "../icons/space-dust-cloud.svg";
import spaceEarth from "../icons/space-earth.svg";
import spaceFrozenOrb from "../icons/space-frozen-orb.svg";
import spaceGalaxy from "../icons/space-galaxy.svg";
import spaceMeteorOutline from "../icons/space-meteor-outline.svg";
import spaceMeteor from "../icons/space-meteor.svg";
import spaceMoonOutline from "../icons/space-moon-outline.svg";
import spaceMoon from "../icons/space-moon.svg";
import spaceOrbitOutline from "../icons/space-orbit-outline.svg";
import spaceOrbit from "../icons/space-orbit.svg";
import spaceOrbital from "../icons/space-orbital.svg";
import spacePlanetCore from "../icons/space-planet-core.svg";
import spacePlanetOutline from "../icons/space-planet-outline.svg";
import spacePlanet from "../icons/space-planet.svg";
import spacePortal from "../icons/space-portal.svg";
import spaceRadialBalance from "../icons/space-radial-balance.svg";
import spaceRadioactive from "../icons/space-radioactive.svg";
import spaceRaiderA from "../icons/space-raider-a.png";
import spaceRaiderB from "../icons/space-raider-b.png";
import spaceRaiderC from "../icons/space-raider-c.png";
import spaceRaiderD from "../icons/space-raider-d.png";
import spaceRingDashed from "../icons/space-ring-dashed.svg";
import spaceRingSegments from "../icons/space-ring-segments.svg";
import spaceRing from "../icons/space-ring.svg";
import spaceRingedPlanet from "../icons/space-ringed-planet.svg";
import spaceRocket from "../icons/space-rocket.svg";
import spaceSatelliteA from "../icons/space-satellite-a.png";
import spaceSatelliteB from "../icons/space-satellite-b.png";
import spaceSatelliteC from "../icons/space-satellite-c.png";
import spaceSatelliteD from "../icons/space-satellite-d.png";
import spaceShieldOutline from "../icons/space-shield-outline.svg";
import spaceShipA from "../icons/space-ship-a.png";
import spaceShipB from "../icons/space-ship-b.png";
import spaceShipC from "../icons/space-ship-c.png";
import spaceShipD from "../icons/space-ship-d.png";
import spaceShipF from "../icons/space-ship-f.png";
import spaceShipG from "../icons/space-ship-g.png";
import spaceShipI from "../icons/space-ship-i.png";
import spaceShipJ from "../icons/space-ship-j.png";
import spaceShipK from "../icons/space-ship-k.png";
import spaceShipL from "../icons/space-ship-l.png";
import spaceShipSidesA from "../icons/space-ship-sides-a.png";
import spaceStarGate from "../icons/space-star-gate.svg";
import spaceStarLarge from "../icons/space-star-large.png";
import spaceStarMedium from "../icons/space-star-medium.png";
import spaceStarSwirl from "../icons/space-star-swirl.svg";
import spaceStationA from "../icons/space-station-a.png";
import spaceStationB from "../icons/space-station-b.png";
import spaceStationC from "../icons/space-station-c.png";
import spaceStation from "../icons/space-station.svg";
import spaceStoneSphere from "../icons/space-stone-sphere.svg";
import spaceSunOutline from "../icons/space-sun-outline.svg";
import spaceSunRays from "../icons/space-sun-rays.svg";
import spaceSun from "../icons/space-sun.svg";
import spaceTargetOutline from "../icons/space-target-outline.svg";
import spaceTwinkle from "../icons/space-twinkle.svg";
import spaceUfo from "../icons/space-ufo.svg";
import spaceVortex from "../icons/space-vortex.svg";
import spaceWaterWorld from "../icons/space-water-world.svg";
import spaceWorld from "../icons/space-world.svg";

export const BUNDLED_SPACE_ICONS: [string, string][] = [
	["space-anomaly.svg", spaceAnomaly],
	["space-asteroid.png", spaceAsteroid],
	["space-atom-outline.svg", spaceAtomOutline],
	["space-beacon-outline.svg", spaceBeaconOutline],
	["space-black-hole.svg", spaceBlackHole],
	["space-comet.svg", spaceComet],
	["space-debris.svg", spaceDebris],
	["space-defense-satellite.svg", spaceDefenseSatellite],
	["space-dots-hex.svg", spaceDotsHex],
	["space-double-ring.svg", spaceDoubleRing],
	["space-dust-cloud.svg", spaceDustCloud],
	["space-earth.svg", spaceEarth],
	["space-frozen-orb.svg", spaceFrozenOrb],
	["space-galaxy.svg", spaceGalaxy],
	["space-meteor-outline.svg", spaceMeteorOutline],
	["space-meteor.svg", spaceMeteor],
	["space-moon-outline.svg", spaceMoonOutline],
	["space-moon.svg", spaceMoon],
	["space-orbit-outline.svg", spaceOrbitOutline],
	["space-orbit.svg", spaceOrbit],
	["space-orbital.svg", spaceOrbital],
	["space-planet-core.svg", spacePlanetCore],
	["space-planet-outline.svg", spacePlanetOutline],
	["space-planet.svg", spacePlanet],
	["space-portal.svg", spacePortal],
	["space-radial-balance.svg", spaceRadialBalance],
	["space-radioactive.svg", spaceRadioactive],
	["space-raider-a.png", spaceRaiderA],
	["space-raider-b.png", spaceRaiderB],
	["space-raider-c.png", spaceRaiderC],
	["space-raider-d.png", spaceRaiderD],
	["space-ring-dashed.svg", spaceRingDashed],
	["space-ring-segments.svg", spaceRingSegments],
	["space-ring.svg", spaceRing],
	["space-ringed-planet.svg", spaceRingedPlanet],
	["space-rocket.svg", spaceRocket],
	["space-satellite-a.png", spaceSatelliteA],
	["space-satellite-b.png", spaceSatelliteB],
	["space-satellite-c.png", spaceSatelliteC],
	["space-satellite-d.png", spaceSatelliteD],
	["space-shield-outline.svg", spaceShieldOutline],
	["space-ship-a.png", spaceShipA],
	["space-ship-b.png", spaceShipB],
	["space-ship-c.png", spaceShipC],
	["space-ship-d.png", spaceShipD],
	["space-ship-f.png", spaceShipF],
	["space-ship-g.png", spaceShipG],
	["space-ship-i.png", spaceShipI],
	["space-ship-j.png", spaceShipJ],
	["space-ship-k.png", spaceShipK],
	["space-ship-l.png", spaceShipL],
	["space-ship-sides-a.png", spaceShipSidesA],
	["space-star-gate.svg", spaceStarGate],
	["space-star-large.png", spaceStarLarge],
	["space-star-medium.png", spaceStarMedium],
	["space-star-swirl.svg", spaceStarSwirl],
	["space-station-a.png", spaceStationA],
	["space-station-b.png", spaceStationB],
	["space-station-c.png", spaceStationC],
	["space-station.svg", spaceStation],
	["space-stone-sphere.svg", spaceStoneSphere],
	["space-sun-outline.svg", spaceSunOutline],
	["space-sun-rays.svg", spaceSunRays],
	["space-sun.svg", spaceSun],
	["space-target-outline.svg", spaceTargetOutline],
	["space-twinkle.svg", spaceTwinkle],
	["space-ufo.svg", spaceUfo],
	["space-vortex.svg", spaceVortex],
	["space-water-world.svg", spaceWaterWorld],
	["space-world.svg", spaceWorld],
];
